service: flight-service

frameworkVersion: '3'

custom:
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  tableName: ${self:service}-table-${self:custom.stage}
  checkInTrigger: ${self:service}-check-in-trigger-${self:custom.stage}
  checkInFlightQueue: ${self:service}-check-in-queue-${self:custom.stage}
  checkInPassengerQueue: ${self:service}-check-in-passenger-queue-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  memorySize: 256
  stage: ${self:custom.stage}
  deploymentBucket:
    name: ${self:service}-deployment-bucket-${self:custom.stage}
    serverSideEncryption: AES256
  apiGateway:
    shouldStartNameWithService: true
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'Fn::GetAtt': [FlightTable, Arn]
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - !GetAtt CheckInFlightQueue.Arn
        - !GetAtt CheckInPassengerQueue.Arn
  environment:
    TABLE_NAME: ${self:custom.tableName}
    CHECK_IN_FLIGHT_SQS_QUEUE_URL: !GetAtt CheckInFlightQueue.QueueUrl
    CHECK_IN_PASSENGER_SQS_QUEUE_URL: !GetAtt CheckInPassengerQueue.QueueUrl

plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket

package:
  individually: false
  patterns:
    - '!test/**'
    - '!src/index.ts'

functions:
  get-flight:
    handler: src/functions/get-flight.handler
    events:
      - httpApi: 'GET /v1/flights'

  get-flight-by-id:
    handler: src/functions/get-flight-by-id.handler
    events:
      - httpApi: 'GET /v1/flights/{id}'

  create-flight:
    handler: src/functions/create-flight.handler
    events:
      - httpApi: 'POST /v1/flights'

  delete-flight:
    handler: src/functions/delete-flight.handler
    events:
      - httpApi: 'DELETE /v1/flights/{id}'

  check-in-start:
    handler: src/functions/check-in-start.handler
    events:
      - eventBridge:
          name: ${self:custom.checkInTrigger}
          description: 'Trigger to run the Check-in event on the Flight Service.'
          enabled: true
          schedule: rate(50 minutes)

  check-in-flight:
    handler: src/functions/check-in-flight-notifier.handler
    events:
      - sqs:
          arn: !GetAtt CheckInFlightQueue.Arn

  check-in-passenger:
    handler: src/functions/check-in-passenger-notifier.handler
    events:
      - sqs:
          arn: !GetAtt CheckInPassengerQueue.Arn

resources:
  - ${file(resources/database.yml)}
  - ${file(resources/queue.yml)}
