service: flight-service

frameworkVersion: '3'

custom:
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  tableName: ${self:service}-table-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  memorySize: 256
  stage: ${self:custom.stage}
  deploymentBucket:
    name: ${self:service}-deployment-bucket-${self:custom.stage}
    serverSideEncryption: AES256
  apiGateway:
    shouldStartNameWithService: true
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'Fn::GetAtt': [FlightTable, Arn]
  environment:
    TABLE_NAME: ${self:custom.tableName}

plugins:
  - serverless-plugin-typescript
  - serverless-deployment-bucket

package:
  individually: false
  patterns:
    - '!test/**'

functions:
  get-flight-by-id:
    handler: src/functions/get-flight.handler
    events:
      - httpApi: 'GET /v1/flights'
  get-flight:
    handler: src/functions/get-flight-by-id.handler
    events:
      - httpApi: 'GET /v1/flights/{id}'
  create-flight:
    handler: src/functions/create-flight.handler
    events:
      - httpApi: 'POST /v1/flights'
  delete-flight:
    handler: src/functions/delete-flight.handler
    events:
      - httpApi: 'DELETE /v1/flights/{id}'

resources:
  - ${file(resources/database.yml)}
